import { SearchResult } from "../../../../types/search"
import { searchResultBuilder } from "../../../../builders/SearchResult"

export const dummySearchResults: SearchResult[] = [
  searchResultBuilder()
    .label(`Form Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("lol")
    .build(),
  searchResultBuilder()
    .label(`Image Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("howdy")
    .build(),
  searchResultBuilder()
    .label(`Data Processing Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Music Composing Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Theme Builder Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`JSON Forms Pipelines`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("project")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Image Node`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("node")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Video Node`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("node")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`JSON Node`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("node")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Separate RGB Node`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("node")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Rust Runtime`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("runtime")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Basic JS Runtime`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("runtime")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Fetch youtube videos graph`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("graph")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Fetch images graph`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("graph")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Fetch tweets`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("graph")
    .url("blablabla")
    .build(),
  searchResultBuilder()
    .label(`Fetch news graph`)
    .createdAt("April 22 2022")
    .author("Regibyte")
    .type("graph")
    .url("blablabla")
    .build(),
]
